// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/drop/config.proto

package drop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is the configuration for the drop outbound handler.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LossPercent is the packet loss rate in percentage (0 - 100).
	LossPercent uint32 `protobuf:"varint,1,opt,name=loss_percent,json=lossPercent,proto3" json:"loss_percent,omitempty"`
	// Direction specifies which direction to apply packet loss: "upload", "download", or "all".
	Direction     string `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_drop_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_drop_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_drop_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetLossPercent() uint32 {
	if x != nil {
		return x.LossPercent
	}
	return 0
}

func (x *Config) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

var File_proxy_drop_config_proto protoreflect.FileDescriptor

// rawDesc encodes the following proto file:
//
//	syntax = "proto3";
//	package xray.proxy.drop;
//	option go_package = "github.com/xtls/xray-core/proxy/drop";
//	message Config {
//	  uint32 loss_percent = 1;
//	  string direction    = 2;
//	}
//
// Binary encoding of the FileDescriptorProto:
//
//	Field 1 (name):         "proxy/drop/config.proto"
//	Field 2 (package):      "xray.proxy.drop"
//	Field 4 (message_type): Config { loss_percent uint32; direction string }
//	Field 8 (options):      go_package = "github.com/xtls/xray-core/proxy/drop"
//	Field 12 (syntax):      "proto3"
const file_proxy_drop_config_proto_rawDesc = "" +
	"\x0a\x17proxy/drop/config.proto" + // field1: name (23 bytes)
	"\x12\x0fxray.proxy.drop" + // field2: package (15 bytes)
	"\x22\x49" + // field4: message_type, length=73
	"\x0a\x06Config" + // Config.name (8 bytes)
	"\x12\x21" + // Config.field[0], length=33
	"\x0a\x0closs_percent" + // field.name="loss_percent"
	"\x18\x01" + // field.number=1
	"\x20\x01" + // field.label=LABEL_OPTIONAL
	"\x28\x0d" + // field.type=TYPE_UINT32=13
	"\x52\x0blossPercent" + // field.json_name="lossPercent"
	"\x12\x1c" + // Config.field[1], length=28
	"\x0a\x09direction" + // field.name="direction"
	"\x18\x02" + // field.number=2
	"\x20\x01" + // field.label=LABEL_OPTIONAL
	"\x28\x09" + // field.type=TYPE_STRING=9
	"\x52\x09direction" + // field.json_name="direction"
	"\x42\x26" + // field8: options, length=38
	"\x5a\x24github.com/xtls/xray-core/proxy/drop" + // go_package (36 bytes)
	"\x62\x06proto3" // field12: syntax

var (
	file_proxy_drop_config_proto_rawDescOnce sync.Once
	file_proxy_drop_config_proto_rawDescData []byte
)

func file_proxy_drop_config_proto_rawDescGZIP() []byte {
	file_proxy_drop_config_proto_rawDescOnce.Do(func() {
		file_proxy_drop_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_drop_config_proto_rawDesc), len(file_proxy_drop_config_proto_rawDesc)))
	})
	return file_proxy_drop_config_proto_rawDescData
}

var file_proxy_drop_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_drop_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.drop.Config
}
var file_proxy_drop_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_drop_config_proto_init() }
func file_proxy_drop_config_proto_init() {
	if File_proxy_drop_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_drop_config_proto_rawDesc), len(file_proxy_drop_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_drop_config_proto_goTypes,
		DependencyIndexes: file_proxy_drop_config_proto_depIdxs,
		MessageInfos:      file_proxy_drop_config_proto_msgTypes,
	}.Build()
	File_proxy_drop_config_proto = out.File
	file_proxy_drop_config_proto_goTypes = nil
	file_proxy_drop_config_proto_depIdxs = nil
}
